upstream_package_name: redhat-cloud-client-configuration
downstream_package_name: redhat-cloud-client-configuration
specfile_path: redhat-cloud-client-configuration.spec

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - centos-stream-8
      - centos-stream-9
      - centos-stream-10
      - fedora-all
      - rhel-7
      - rhel-8
      - rhel-9

  - job: copr_build
    trigger: commit
    branch: main
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-8
      - centos-stream-9
      - centos-stream-10
      - fedora-all
      - rhel-8
      - rhel-9
