name: Build RPM

on: push

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install python3-rpm, create venv and install tito
      run: |
        sudo apt-get install python3-rpm
        python3 -m venv tito_venv
        source tito_venv/bin/activate
        pip install tito rpm
        sudo apt-cache search systemd

    - name: Build tito
      run: |
        source tito_venv/bin/activate && tito build --test --rpm --verbose --debug -o /tmp/tito_build --no-cleanup
        ls -ltr /tmp/tito_build

    - uses: actions/upload-artifact@v3
      with:
        name: RPM
        path: /tmp/tito_build/*
